
# 配置中心
xconf:
  zkAddress: 192.168.7.68:2181,192.168.7.69:2181,192.168.7.70:2181
  groups: mysql,redis


# dubbo
dubbo:
  registry:
    protocol: zookeeper
    address: 192.168.7.68:2181,192.168.7.69:2181,192.168.7.70:2181
    timeout: 5000
  consumer:
    timeout: 100000
    retries: 0
    filter: -unchecked
    validation: true
    check: false


life:
  props:
    frontHtmlUrl: https://life-m.gegejia.com
    sellerH5Url: ${life.props.frontHtmlUrl}/shop
    partnerH5Url: ${life.props.frontHtmlUrl}/partner
    es:
      cluster-name: life
      node-list: 192.168.0.246:9300|192.168.0.247:9300|192.168.0.248:9300
      node-master: false
      node-data: false
      node-ingest: false
      client-transport-sniff: true

# ons配置
ons:
  prop:
    accessKey: LTAI9TxYmVRUdZuV
    secretKey: ljjrYfoNmKq6IZKa87AMCK14adYZ2M
    producerId: PID_GGJ_BUSINESS_LIFE_PROD
    sendMsgTimeoutMillis: 3000
    consumeThreadNums: 20
    topic: GGJ_TOPIC_BUSINESS_LIFE_PROD
    env: prod
    tags:
      - TAG_LIFE_LOGISTICS_SUBSCRIBE
      - TAG_LIFE_PRODUCT_UPDATE
      - TAG_LIFE_MINI_ORDER_NOTIFY
      - TAG_LIFE_CLEAN_OLD_FORMID