server:
    port: 10003

spring:
  profiles:
    include: common-dev

system:
  props:
    frontServer: redirect:http://localhost:10003
#    frontServer: forward:/home
    platform:
      type: 39
      cacheKey: admin_orders_platform_types

cas:
  clientHostUrl: http://localhost:10003
  serverHostUrl: http://testadmin1.gegejia.com/ygg-sso

white:
  urls: /*.js;/*.css;/*.jpg;/swagger-resources/*;/error;/webjars/*;/swagger-ui/*;v2/*;